runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_jbtb022x:gumdj3ejmnoq54r3chkskhs2g4@ds147799.mlab.com:47799/heroku_jbtb022x
  APP_ID: 6a7b0123-98c2-4296-a60a-4a4d29ebb1de
  MASTER_KEY: vL21EVcjABSrw7oNBkT853UbP02sVB8g
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  